export const blurPlaceholders = {
  profile: "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADwBACdASoYABoAPu1qqVAppiOiqA1RMB2JQBmaATaH6ItU5maU5ah9TBDBPuWcESQA/oNCKex2hR42A3w6/V6e9RC2fzXzXtn9YoaTCtLRYYCVjryToCVvRPVvqqMrWWYhb9GBG2p9EzOVjKfryOVkWkuJjzN08eBX2N7eeCoCFEoIIU9uFNqb0oO0xaUDRjplX+QNOE7OvEv9fMofDS5AG7fBEwJDhyx7OsfORqisAA==",
} as const;

export type BlurKey = keyof typeof blurPlaceholders;
